### ISSUE TITLE
New RePIT repository

### ISSUE THREAD

**Issue by 41monster** [41monster/RePIT_NaturalCirculation2D#1]
@shilaj @chinge55 

Hi Shilaj,

As our RePIT project begins in earnest, I have created a new repository (RePIT). Please accept my invitation and keep updating the code and issues currently during development. Please let me know if you have any problems with github permissions.

**Comment by shilaj** [comment]
@41monster Okay Professor.

**Comment by sunbingxin-jpg** [comment]
Hello, I have a problem running the code.

**Comment by sunbingxin-jpg** [comment]
![Uploading 报错.png…]()

**Comment by sunbingxin-jpg** [comment]
/
![Uploading error.png…]()

**Comment by sunbingxin-jpg** [comment]
10.03csv is not found.

**Comment by shilaj** [comment]
Hi @sunbingxin-jpg, sorry to hear about your problem. That is because there is not csv file for 10.03 time step in the DataSample directory. If you are just trying to run the codes, you can just create the dummy input for the 10.03 time step or in the code you can limit the loop for just 10.02 seconds (maybe this will not be a good option, because I think in the code we are reducing the time step up to 2 or 3 level). 

**For the dummy input, keep in mind:**
1. Headers should be: ,T,p,p_rgh,Ux,Uy,Ux
2. Number of data points are: 40000

Here is the code (saving the dummy input): 
```
import numpy as np
import pandas as pd

dummy_input = np.random.randn(40000,6)
df = pd.DataFrame(dummy_input, columns=["T","p","p_rgh","U_x","U_y","U_z"])
time_step = 10.03
df.to_csv(f"./DataSample/traindata{time_step}.csv", index=True)
```
Please, let us know if you have further queries. Thank you.

**Note:** I know this way we can't re-create the results, but I hope it will help you run the codes in the first place.

**Comment by sunbingxin-jpg** [comment]
Thank you very much for your reply. I wanted to run code to solve the ns equation problem, but I also encountered some other issues. In the centers file, are x, y, and z coordinates? I tried to build a matrix with an index of 520 * 520 in my dataset, but according to the index, it exceeded the boundary.&nbsp;Thank you very much for running your code. Figure 1 is your center file, and Figure 2 is my coordinate file.






发自我的iPhone


------------------ Original ------------------
From: Baral ***@***.***&gt;
Date: Mon,Dec 2,2024 9:54 AM
To: 41monster/RePIT_NaturalCirculation2D ***@***.***&gt;
Cc: sunbingxin-jpg ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [41monster/RePIT_NaturalCirculation2D] New RePIT repository(Issue #1)





 
Hi @sunbingxin-jpg, sorry to hear about your problem. That is because there is not csv file for 10.03 time step in the DataSample directory. If you are just trying to run the codes, you can just create the dummy input for the 10.03 time step or in the code you can limit the loop for just 10.02 seconds (maybe this will not be a good option, because I think in the code we are reducing the time step up to 2 or 3 level).
 
For the dummy input, keep in mind:
  
Headers should be: ,T,p,p_rgh,Ux,Uy,Ux
 
Number of data points are: 40000
  
Here is the code (saving the dummy input):
 import numpy as np import pandas as pd dummy_input = np.random.randn(40000,6) df = pd.DataFrame(x, columns=["T","p","p_rgh","U_x","U_y","U_z"]) time_step = 10.03 df.to_csv(f"./DataSample/{time_step}.csv", index=True)  
Please, let us know if you have further queries. Thank you.
 
Note: I know this way we can't re-create the results, but I hope it will help you run the codes in the first place.

**Comment by shilaj** [comment]
Hi @sunbingxin-jpg, yes the center file is mesh dependent. Now, we have updated our code can you please try on the latest version of the code i.e. **tag:v2.0**. We basically have a configuration file, where you can set the parameters to your need. And, only requirement regarding the dataset is, it must be in the format defined in the Assets/natural_convection directory. 
I mean, if you want to train your variables ["U","p","T"] then the training dataset must be the U_{time_step}.npy and so on. 
Can you please try it on and see if it solves your problem?

**Comment by sunbingxin-jpg** [comment]
Thank you very much for your reply. I will try running your updated code！



发自我的iPhone


------------------ Original ------------------
From: Baral ***@***.***&gt;
Date: Tue,Dec 3,2024 11:01 AM
To: 41monster/RePIT_NaturalCirculation2D ***@***.***&gt;
Cc: sunbingxin-jpg ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [41monster/RePIT_NaturalCirculation2D] New RePIT repository(Issue #1)





 
Hi @sunbingxin-jpg, yes the center file is mesh dependent. Now, we have updated our code can you please try on the latest version of the code i.e. tag:v2.0. We basically have a configuration file, where you can set the parameters to your need. And, only requirement regarding the dataset is, it must be in the format defined in the Assets/natural_convection directory.
 I mean, if you want to train your variables ["U","p","T"] then the training dataset must be the U_{time_step}.npy and so on.
 Can you please try it on and see if it solves your problem?

**Comment by shilaj** [comment]
Okay. If you face any problems, feel free to open a new issue. For now, I am closing the issue. Thank you.

**Comment by sunbingxin-jpg** [comment]
OK，thank you very much.



发自我的iPhone


------------------ Original ------------------
From: Baral ***@***.***&gt;
Date: Tue,Dec 3,2024 11:08 AM
To: 41monster/RePIT_NaturalCirculation2D ***@***.***&gt;
Cc: sunbingxin-jpg ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [41monster/RePIT_NaturalCirculation2D] New RePIT repository(Issue #1)





 
Okay. If you face any problems, feel free to open a new issue. For now, I am closing the issue. Thank you.

**Comment by sunbingxin-jpg** [comment]
I'm sorry to trouble you, but I have two questions. Firstly, I would like to use data from 5-5.05 to predict time periods that are not available in the dataset, such as 5.06. Secondly, the predicted file generated by the code is a 200 * 200 matrix, and the original real value is 1 * 500. How should I compare.



发自我的iPhone


------------------ Original ------------------
From: Baral ***@***.***&gt;
Date: Tue,Dec 3,2024 11:08 AM
To: 41monster/RePIT_NaturalCirculation2D ***@***.***&gt;
Cc: sunbingxin-jpg ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [41monster/RePIT_NaturalCirculation2D] New RePIT repository(Issue #1)





 
Okay. If you face any problems, feel free to open a new issue. For now, I am closing the issue. Thank you.

**Comment by shilaj** [comment]
Hi @sunbingxin-jpg, the thing is, we need to have original data also for this method, because for the boundary values we are attaching to the predicted values from the ground truth. Basically, if you have [200,200] grid, the Neural Network predicts the internal node: [198,198] and we give the boundary values from original data and make it [200,200] again which is now the new input to the Neural Network to predict the next time step. 

Secondly, I didn't get what do you mean by original real value shape is [1,500]. Because for the natural convection we are trying, the input data shape is [39402,5] **(which is obtained after extracting the feature from the true value of shape [200,200])** for each variable and the output from the neural network is of shape [39204,1]. So, can you please point out how are you getting this shape?

**Comment by sunbingxin-jpg** [comment]
Hello, let me take a picture to explain. (500,1) is what is displayed when I open the first picture, and the second picture is the shape generated after I run runner.py. The input data you are talking about are the five variables in the third picture. Is the code you uploaded for the second time a demonstration of processing real data? Because the results of the two code generation are not consistent. I just want to process my own data, which is three variables. Each variable has 270663 rows. When I ran the original code, I found that the index was out of bounds. It may be that the index I constructed was wrong. Because I found that x in the original centers.csv is increasing.








Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 下午2:04
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] New RePIT repository (Issue #1)





 
Hi @sunbingxin-jpg, the thing is, we need to have original data also for this framework, because for the boundary values we are attaching to the predicted values from the ground truth. Basically, if you have [200,200] grid, the Neural Network predicts the internal node: [198,198] and we give the boundary values from original data and make it [200,200] again which is now the new input to the Neural Network to predict the next time step.
 
Secondly, I didn't get what do you mean by original real value shape is [1,500]. Because for the natural convection we are trying, the input data shape is [39402,5] (which is obtained after extracting the feature from the true value of shape [200,200]) for each variable and the output from the neural network is of shape [39204,1]. So, can you please point out how are you getting this shape?
